PasswordManager.Web/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PasswordManager.Web.Data;
using PasswordManager.Web.Models;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using PasswordManager.Core.Extensions;
using PasswordManager.Web.Helpers;

namespace PasswordManager.Web.Controllers
{
    [Authorize(Roles = "User")]
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public NotesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Notes.Include(n => n.AppUser).Where(n => n.UserId == _userManager.GetUserId(HttpContext.User));
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string cryptoKey = this.RetriveCryptoHash();
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .Include(n => n.AppUser)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            if (cryptoKey == null)
            {
                return RedirectToAction("VerifyPassword", "Account", new { ReturnUrl = UriHelper.GetDisplayUrl(Re‌​quest) });
            }
            note.Decrypt(cryptoKey);
            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            if (this.RetriveCryptoHash() == null)
            {
                return RedirectToAction("VerifyPassword", "Account", new { ReturnUrl = UriHelper.GetDisplayUrl(Re‌​quest) });
            }
            this.KeepCryptoHash();
            return View(new Note { UserId = _userManager.GetUserId(HttpContext.User) });
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Login,Password,Other,Changed,UserId")] Note note)
        {
            string cryptoKey = this.RetriveCryptoHash();
            if (cryptoKey == null)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                note.Encrypt(cryptoKey);
                note.Changed = DateTimeOffset.Now;
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(new Note { UserId = _userManager.GetUserId(HttpContext.User) });
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string cryptoKey = this.RetriveCryptoHash();
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes.SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            if (cryptoKey == null)
            {
                return this.CallVerifyPassword();
            }
            note.Decrypt(cryptoKey);
            this.KeepCryptoHash();
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Login,Password,Other,Changed,UserId")] Note note)
        {
            string cryptoKey = this.RetriveCryptoHash();
            if (id != note.Id || cryptoKey == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    note.Encrypt(cryptoKey);
                    note.Changed = DateTimeOffset.Now;
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string cryptoKey = this.RetriveCryptoHash();
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .Include(n => n.AppUser)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            if (cryptoKey == null)
            {
                return RedirectToAction("VerifyPassword", "Account", new { ReturnUrl = UriHelper.GetDisplayUrl(Re‌​quest) });
            }
            note.Decrypt(cryptoKey);
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Notes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Notes.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool NoteExists(int id)
        {
            return _context.Notes.Any(e => e.Id == id);
        }
    }
}

PasswordManager.Web/Controllers/UserViewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PasswordManager.Web.Data;
using PasswordManager.Web.Models;

namespace PasswordManager.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserViewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserViewController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Users;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            IList<String> roles = new List<string> { "Роль не определена" };
            if (user == null)
            {
                return NotFound();
            }
            else
            {   
                roles = await _userManager.GetRolesAsync(user);
            }
            ViewData["RolesForThisUser"] = roles;
            return View(user);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

PasswordManager.Web/Views/Shared/Info.cshtml
@{
    ViewData["Title"] = "Info";
}

<h2>Info</h2>
<div>
    <p>@ViewData["Message"]</p>
</div>

PasswordManager.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title – Password Manager</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Password Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="UserView" asp-action="Index">Пользователи</a></li>
                    }
                    else if (User.IsInRole("User"))
                    {
                        <li><a asp-area="" asp-controller="Notes" asp-action="Index">Пароли</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="About">О программе</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Контакт</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – IdamkinI</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>